before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "windows"
      - "darwin"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: "windows"
        goarch: "arm"
      - goos: "windows"
        goarch: "arm64"
archives:
  - files:
      - LICENSE
      - README.md
    wrap_in_directory: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
